### ISSUE TITLE
W/tango_client_api: TangoErrorType TangoService_getPoseAtTime(double, TangoCoordinateFramePair, TangoPoseData*): Failed to query a pose.

### ISSUE THREAD

**Issue by fangxu622** [occamLab/tango_ros_bridge#14]
when i click the connect button ,the app is shutdown~~

```
D/skia: onFlyCompress
E/AndroidRuntime: FATAL EXCEPTION: Thread-353
    Process: com.projecttango.examples.cpp.hellomotiontracking, PID: 14080
    java.lang.NullPointerException: Destination address is null
        at java.net.DatagramSocket.send(DatagramSocket.java:302)
        at com.projecttango.examples.cpp.hellomotiontracking.HelloMotionTrackingActivity$2$7.run(HelloMotionTrackingActivity.java:571)
        at java.lang.Thread.run(Thread.java:818)
W/System.err: java.net.UnknownHostException: Unable to resolve host "192.168.43.106:11311": No address associated with hostname
W/System.err:     at java.net.InetAddress.lookupHostByName(InetAddress.java:470)
        at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)
        at java.net.InetAddress.getAllByName(InetAddress.java:215)
        at java.net.Socket.tryAllAddresses(Socket.java:109)
        at java.net.Socket.<init>(Socket.java:178)
        at java.net.Socket.<init>(Socket.java:150)
        at com.projecttango.examples.cpp.hellomotiontracking.TCPCommunicator$InitTCPClientTask.doInBackground(TCPCommunicator.java:133)
        at com.projecttango.examples.cpp.hellomotiontracking.TCPCommunicator$InitTCPClientTask.doInBackground(TCPCommunicator.java:120)
        at android.os.AsyncTask$2.call(AsyncTask.java:295)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
    Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
        at libcore.io.Posix.android_getaddrinfo(Native Method)
        at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:55)
        at java.net.InetAddress.lookupHostByName(InetAddress.java:451)
    	... 12 more
I/System.out: Beacon starting
I/tango_client_api: void TangoService_disconnect(): Disconnecting from Tango...
D/skia: onFlyCompress
I/Process: Sending signal. PID: 14080 SIG: 9
Application terminated.
```

and before click connect button, the debug info output like this

```
12/23 12:18:54: Launching ros_streamer
$ adb shell am start -n "com.projecttango.examples.cpp.hellomotiontracking/com.projecttango.examples.cpp.hellomotiontracking.HelloMotionTrackingActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Client not ready yet..Waiting for process to come online
Connected to process 15198 on device lenovo-lenovo_pb2_690n-8fa8c265
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
D/lenovotintstatusbar: makeVisible, component = ComponentInfo{com.projecttango.examples.cpp.hellomotiontracking/com.projecttango.examples.cpp.hellomotiontracking.HelloMotionTrackingActivity}, flags = 0x1810100, sysuiVis = 0x0
    Check tint and icon theme, false, false
I/tango_client_api: TangoErrorType TangoService_setBinder(void*, void*): Passing back the binder on the client end...
I/hello-tango-jni: Successfully bound to serivice
I/tango_client_api: void* TangoService_getConfig(TangoConfigType): Getting config...
I/tango_client_api: void* TangoService_getConfig(TangoConfigType): Done getting config.
I/hello-tango-jni: ENABLED COLOR CAMERA SUCCESSFULLY 1
    ENABLED DRIFT CORRECTION SUCCESSFULLY 1
    CONFIG SET!
    Starting to setup the  mutexes
I/tango_client_api: TangoErrorType TangoService_connectOnTangoEvent(void (*)(void*, const TangoEvent*), ...): Connecting callbacks...
    TangoErrorType TangoService_connectOnTangoEvent(void (*)(void*, const TangoEvent*), ...): Done connecting callbacks.
    TangoErrorType TangoService_connectOnFrameAvailable(TangoCameraId, void*, void (*)(void*, TangoCameraId, const TangoImageBuffer*)): Connecting callbacks...
I/tango_client_api: TangoErrorType TangoService_connectOnFrameAvailable(TangoCameraId, void*, void (*)(void*, TangoCameraId, const TangoImageBuffer*)) called for cam id(2) before TangoService_connect(). Callback will be registered on next call to TangoService_connect().
I/hello-tango-jni: FISHEYE FRAME AVAILABLE WAS SUCCESSFUL!
    PAUL: setting up color frame callbacks
I/tango_client_api: TangoErrorType TangoService_connectOnFrameAvailable(TangoCameraId, void*, void (*)(void*, TangoCameraId, const TangoImageBuffer*)): Connecting callbacks...
I/tango_client_api: TangoErrorType TangoService_connectOnFrameAvailable(TangoCameraId, void*, void (*)(void*, TangoCameraId, const TangoImageBuffer*)) called for cam id(0) before TangoService_connect(). Callback will be registered on next call to TangoService_connect().
I/tango_client_api: TangoErrorType TangoService_connect(void*, TangoConfig): Connecting to Tango...
E/tango_client_api: TangoErrorType TangoService_connect(void*, TangoConfig): Enable color camera
I/tango_client_api: TangoErrorType TangoService_connect(void*, TangoConfig): Successfully connected to Tango.
I/tango_client_api: TangoErrorType TangoService_getCameraIntrinsics(TangoCameraId, TangoCameraIntrinsics*): Getting camera intrinsics...
I/tango_client_api: TangoErrorType TangoService_getCameraIntrinsics(TangoCameraId, TangoCameraIntrinsics*): Done getting camera intrinsics.
I/Choreographer: Skipped 155 frames!  The application may be doing too much work on its main thread.
I/tango_client_api: TangoErrorType TangoService_getCameraIntrinsics(TangoCameraId, TangoCameraIntrinsics*): Getting camera intrinsics...

.......



I/tango_client_api: TangoErrorType TangoService_getCameraIntrinsics(TangoCameraId, TangoCameraIntrinsics*): Getting camera intrinsics...
I/tango_client_api: TangoErrorType TangoService_getCameraIntrinsics(TangoCameraId, TangoCameraIntrinsics*): Done getting camera intrinsics.
I/tango_client_api: TangoErrorType TangoService_getCameraIntrinsics(TangoCameraId, TangoCameraIntrinsics*): Getting camera intrinsics...
I/tango_client_api: TangoErrorType TangoService_getCameraIntrinsics(TangoCameraId, TangoCameraIntrinsics*): Done getting camera intrinsics.
I/System.out: PointCloud 148025
I/System.out: PointCloud 148293
I/System.out: PointCloud 148261
I/System.out: PointCloud 148189
I/System.out: PointCloud 148105
I/tango_client_api: TangoErrorType TangoService_getCameraIntrinsics(TangoCameraId, TangoCameraIntrinsics*): Getting camera intrinsics...
I/tango_client_api: TangoErrorType TangoService_getCameraIntrinsics(TangoCameraId, TangoCameraIntrinsics*): Done getting camera intrinsics.
I/tango_client_api: TangoErrorType TangoService_getCameraIntrinsics(TangoCameraId, TangoCameraIntrinsics*): Getting camera intrinsics...
I/tango_client_api: TangoErrorType TangoService_getCameraIntrinsics(TangoCameraId, TangoCameraIntrinsics*): Done getting camera intrinsics.
I/System.out: PointCloud 148117
I/System.out: PointCloud 147377
I/System.out: PointCloud 148141
I/System.out: Beacon starting
I/tango_client_api: void TangoService_disconnect(): Disconnecting from Tango...
I/System.out: PointCloud 147985
W/tango_client_api: TangoErrorType TangoService_getPoseAtTime(double, TangoCoordinateFramePair, TangoPoseData*): Failed to query a pose.
    TangoErrorType TangoService_getPoseAtTime(double, TangoCoordinateFramePair, TangoPoseData*): Failed to query a pose.
    TangoErrorType TangoService_getPoseAtTime(double, TangoCoordinateFramePair, TangoPoseData*): Failed to query a pose.
    TangoErrorType TangoService_getPoseAtTime(double, TangoCoordinateFramePair, TangoPoseData*): Failed to query a pose.
W/tango_client_api: TangoErrorType TangoService_getPoseAtTime(double, TangoCoordinateFramePair, TangoPoseData*): Failed to query a pose.
I/tango_client_api: TangoErrorType TangoService_getCameraIntrinsics(TangoCameraId, TangoCameraIntrinsics*): Getting camera intrinsics...
I/tango_client_api: TangoErrorType TangoService_getCameraIntrinsics(TangoCameraId, TangoCameraIntrinsics*): Done getting camera intrinsics.
W/tango_client_api: TangoErrorType TangoService_getPoseAtTime(double, TangoCoordinateFramePair, TangoPoseData*): Failed to query a pose.
    TangoErrorType TangoService_getPoseAtTime(double, TangoCoordinateFramePair, TangoPoseData*): Failed to query a pose.
W/tango_client_api: TangoErrorType TangoService_getPoseAtTime(double, TangoCoordinateFramePair, TangoPoseData*): Failed to query a pose.
    TangoErrorType TangoService_getPoseAtTime(double, TangoCoordinateFramePair, TangoPoseData*): Failed to query a pose.
    TangoErrorType TangoService_getPoseAtTime(double, TangoCoordinateFramePair, TangoPoseData*): Failed to query a pose.
I/tango_client_api: TangoErrorType TangoService_getCameraIntrinsics(TangoCameraId, TangoCameraIntrinsics*): Getting camera intrinsics...
I/tango_client_api: TangoErrorType TangoService_getCameraIntrinsics(TangoCameraId, TangoCameraIntrinsics*): Done getting camera intrinsics.
W/tango_client_api: TangoErrorType TangoService_getPoseAtTime(double, TangoCoordinateFramePair, TangoPoseData*): Failed to query a pose.
W/tango_client_api: TangoErrorType TangoService_getPoseAtTime(double, TangoCoordinateFramePair, TangoPoseData*): Failed to query a pose.
    TangoErrorType TangoService_getPoseAtTime(double, TangoCoordinateFramePair, TangoPoseData*): Failed to query a pose.
    TangoErrorType TangoService_getPoseAtTime(double, TangoCoordinateFramePair, TangoPoseData*): Failed to query a pose.
    TangoErrorType TangoService_getPoseAtTime(double, TangoCoordinateFramePair, TangoPoseData*): Failed to query a pose.
W/tango_client_api: TangoErrorType TangoService_getPoseAtTime(double, TangoCoordinateFramePair, TangoPoseData*): Failed to query a pose.
    TangoErrorType TangoService_getPoseAtTime(double, TangoCoordinateFramePair, TangoPoseData*): Failed to query a pose.
    TangoErrorType TangoService_getPoseAtTime(double, TangoCoordinateFramePair, TangoPoseData*): Failed to query a pose.
    TangoErrorType TangoService_getPoseAtTime(double, TangoCoordinateFramePair, TangoPoseData*): Failed to query a pose.
```

**Comment by fangxu622** [comment]
@pinardemetci @DhashS @xieruishen

**Comment by fangxu622** [comment]
my tango device lenovo phab 2 pro ,andriod 6.01 ~using android-ndk r14b 16b ~~~desktop environment :ubuntu 16.04 kinetic~~
